### ISSUE TITLE
Semantic Highlight Is Not Enabled.

### ISSUE THREAD

**Issue by bittervan** [IWANABETHATGUY/tower-lsp-boilerplate#1]
I am a newbie engineering a vscode extension for out compiler course project.
It seems that the semantic highlight is not enabled by default?
![Screenshot_20220424_184337](https://user-images.githubusercontent.com/57927141/164972678-a671e5a6-3e87-4f17-8181-b5bba2226bc9.png)
 How should I turn this on?

**Comment by bittervan** [comment]
It seems that only buildin themes should be applied?

**Comment by IWANABETHATGUY** [comment]
try to add this line into your `settings.json`
```json
{
//.. snip
 "editor.semanticHighlighting.enabled": true,
}
```

**Comment by bittervan** [comment]
> 

Works fine! This is great work. Thank you for building this template. It helps so much for people like me who wants to build something like this but can find nothing to read about.

**Comment by IWANABETHATGUY** [comment]
> 

I am glad to see this project could help you
