### ISSUE TITLE
Inlay hint doesn't work

### ISSUE THREAD

**Issue by LSTM-Kirigaya** [IWANABETHATGUY/tower-lsp-boilerplate#11]
I am using tower lsp to implment inlay hints, but I have some trouble for its trigger. So I want to meet some inspirations in the project, but when I launch client in your project in vscode extension development mode, inlay hint doesn't work as well:

![image](https://github.com/user-attachments/assets/6422845f-22c3-4ae1-97fc-339e773ae435)

I will be glad if I can be offered some valuable suggestions :D

**Comment by IWANABETHATGUY** [comment]
Can you check if your `Editor.inlay` is enable? 
![image](https://github.com/user-attachments/assets/b5c818da-3a7a-4c40-8b76-29ac96293b84)

**Comment by LSTM-Kirigaya** [comment]
Editor.inlay is on.

I found the problem! Your codes are right, it's the version of `vscode-languageclient` to be blamed. I usually use `vscode-languageclient@7.0.0` for development, but obviously, the version doesn't support LSP>=3.17.0, where inlay hints feature is proposed. So the solution is to upgrade `vscode-languageclient` to newest `9.0.1`. Here is my `package.json` for client

```json
{
	"name": "nrs-language-client",
	"description": "VSCode part of a language server",
	"license": "MIT",
	"version": "0.0.1",
    "main": "../dist/extension.js",
	"engines": {
		"vscode": "^1.85.0"
	},
    "activationEvents": [
        "onLanguage:nrs"
    ],
    "contributes": {
        "languages": [
            {
                "id": "nrs",
                "extensions": [
                    ".nrs"
                ]
            }
        ]
    },
	"dependencies": {
		"vscode-languageclient": "^9.0.1"
	},
	"devDependencies": {
		"@types/node": "^17.0.18",
		"@types/vscode": "1.86.0",
		"vscode-test": "^1.3.0"
	}
}
```

Have a nice day! :D
