### ISSUE TITLE
Errors with latest rust and proposed fixes

### ISSUE THREAD

**Issue by thomasaarholt** [IWANABETHATGUY/tower-lsp-boilerplate#9]
- I got `unknown feature 'proc_macro_span_shrink'`, realized that it was a no longer required feature of `proc-macro2` which is a requirement of `tower-lsp`, so updated tower-lsp to 0.20.0 to fix:
`tower-lsp = { version = "0.20.0", features = ["proposed"]}`

I am not currently able to run the debugger successfully in VSCode (F5). I'm not used to typescript, so I might be doing something wrong, but in VSCode I get a bunch of errors with both typescript 4.6.3 and 5.4.5, as well as this error when I run the debugger:

```
(node:47805) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
```

Any chance you could take a look and maybe clean this up? It would be really nice to have an interactive environment to test the LSP in!

**Comment by IWANABETHATGUY** [comment]
I have bumped the version of `tower-lsp`, but I can't reproduce second `warning`.

**Comment by IWANABETHATGUY** [comment]
![image](https://github.com/IWANABETHATGUY/tower-lsp-boilerplate/assets/17974631/9ba09bab-ed0d-407d-983a-bd59e113c6e9)
There is no `Buffer` api usage in my codebase, so there is nothing I could do to eliminate this warning.
